<script>
  import { Tile } from "carbon-components-svelte";
</script>

<h2>Nostrocket Funding</h2>
<Tile
  ><p>Merits are something akin to equity in a Rocket.</p>
  <p>
    <em>All</em> revenue generated by a Rocket goes <em>directly</em> to the merit
    holders (Nostrocket is strictly non-custodial).
  </p>
  <p>
    Merits are only ever produced in response to work being completed - usually a merged pull request.
  </p>

  <p>
    Contributors may at times want to recieve Bitcoin in exchange for their work, rather than Merits. This is the <em>only</em> way
    non-contributors can acquire merits in a Rocket.
  </p>
  <p>When Merits become available to sponsors, they will be offered to people in the order in which they joined the funding queue.</p>
  <p>
    It's not currently possible to join the funding queue. This feature is
    coming soon.
  </p>
</Tile>
